### ISSUE TITLE
Build omits creating bin

### ISSUE THREAD

**Issue by teledyn** [baharsateli/tdb-exporter#2]
I found I had to make the following change to get a clean compile on Ubuntu 17.10

`diff --git a/build.xml b/build.xml
index 03b3e79..868e1bb 100644
--- a/build.xml
+++ b/build.xml
@@ -58,6 +58,7 @@
   </target>
   
   <target name="compile" depends="resolve" description="Compile the source" >
+        <mkdir dir="${bin.dir}"/>
       <javac srcdir="${src.dir}" debug="true" debuglevel="lines,vars,source" destdir="${bin.dir}">
           <classpath refid="compile.classpath" />
       </javac>
`

**Comment by baharsateli** [comment]
Thanks for reporting this! I updated the Ant build file.
